spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: #not indicated for safety reasons
            clientSecret: #not indicated for safety reasons